"""Add certifications, achievements, and projects fields

Revision ID: 62f40262f756
Revises: 9c2f7a64594c
Create Date: 2025-02-22 15:58:54.189165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f40262f756'
down_revision = '9c2f7a64594c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('achievements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('projects', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Text(),
               nullable=True,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               nullable=False,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('projects')
        batch_op.drop_column('achievements')
        batch_op.drop_column('certifications')

    # ### end Alembic commands ###
